application: resolveref-hrd
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: django
  version: "latest"

handlers:
- url: /
  script: pubref.application

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /ref/(.*)/(.*)
  script: pubref.application

- url: /ref/(.*)
  script: pubref.application

- url: /search
  script: pubref.application

- url: /suggestjournal
  script: pubref.application

- url: /verify/(.*)/(.*)
  script: pubref.application

- url: /verify/(.*)
  script: pubref.application
